export const pkmnAlias: { [key: string]: string } = {
    "nidoran-f": "Nidoran ♀",
    "nidoran-m": "Nidoran ♂",
    "tapu-koko": "Tapu Koko",
    "tapu-lele": "Tapu Lele",
    "tapu-bulu": "Tapu Bulu",
    "tapu-fini": "Tapu Fini",
    "type-null": "Type: Null",
    "porygon-z": "Porygon Z",
    "walking-wake": "Walking Wake",
    "iron-leaves": "Iron Leaves",
    "slither-wing": "Slither Wing",
    "roaring-moon": "Roaring Moon",
    "flutter-mane": "Flutter Mane",
    "raging-bolt": "Raging Bolt",
    "iron-valiant": "Iron Valiant",
    "iron-jugulis": "Iron Jugulis",
    "iron-moth": "Iron Moth",
    "iron-thorns": "Iron Thorns",
    "scream-tail": "Scream Tail",
    "brute-bonnet": "Brute Bonnet",
    "sandy-shocks": "Sandy Shocks",
    "iron-treads": "Iron Treads",
    "mr-mime": "Mr. Mime",
    "ho-oh": "Ho-Oh",
    "mime-jr": "Mime Jr.",
    "great-tusk": "Great Tusk",
    "iron-hands": "Iron Hands",
    "gouging-fire": "Gouging Fire",
    "iron-boulder": "Iron Boulder",
    "iron-bundle": "Iron Bundle",
    "iron-crown": "Iron Crown",
    "mr-rime": "Mr. Rime",
}